### ISSUE TITLE
number of layers in weight file

### ISSUE THREAD

**Issue by DrraBL** [renato145/3D-ORGAN#1]

**Comment by renato145** [comment]
Hi,
The files on `final_model` are already trained, to check the results you should look at the view_results.ipynb notebook.
The script run_experiments.sh is supposed to do the training from scratch (you can change `-o data/final_model` to point to an empty folder to try this).
One problem you may encounter is the version of the libraries that I used (at that time my coding skills were poor and I didn't note the versions :C). I plan to implement the code in a cleaner way but I can't promise that will be soon.

**Comment by dardaa** [comment]
Hi
thank for your reply but i resolved this issue i understand well the code
but i had this error about the number of the layer:You are trying to load a weight file containing 18 layers into a model with 21 layers.
Also i wanna ask you sir about the dataset i want to try with my own 3d mesh saved in npz file not voxel it's mesh how i can do that. please let me know. thank you

**Comment by Tanmay-2106** [comment]
Hi, can you provide the Larco dataset ? It would be of great help. 

Thanks!
