### ISSUE TITLE
Environment for training

### ISSUE THREAD

**Issue by nikwl** [renato145/3D-ORGAN#2]
Hi!

I understand that this is pretty late, but would you be able to release your requirements.txt or conda yaml file? I'm attempting to use the codebase to train on a new dataset but I'm not able to get it to work with modern hardware. Thanks!

**Comment by nikwl** [comment]
In case anyone comes along and has a similar issue, I was able to get the environment to work after several hours of messing around with dependencies. Here's what I did: 

1) Install tensorflow using conda
```
conda create -n 3d-organ tensorflow-gpu==1.14.0
```

2) Install the remainder of the dependencies using pip
```
click==7.1.2
future==0.18.2
google-pasta==0.2.0
joblib==1.1.0
Keras==2.3.1
Keras-Applications==1.0.8
libmesh==0.0.0
numpy==1.16.0
protobuf==3.19.1
PyYAML==6.0
scikit-learn==0.23.2
scipy==1.5.2
tensorboard==1.14.0
tensorflow-estimator==1.14.0
termcolor==1.1.0
threadpoolctl==3.0.0
torch==1.5.0
h5py==2.10.0
```

Best of luck.

**Comment by renato145** [comment]
Thanks, I will add the environment file

**Comment by Tanmay-2106** [comment]
Hello, could you please provide the Larco dataset ? It would be of great help. 

Thanks!
